name = input ("Enter A Name ")
level1 = input ("Enter A Place Name ")
level2 = input ("Enter Another Place Name ")
level3 = input ("Enter Another Place Name ")
level4 = input ("Enter Another Place Name ")
boss = input ("Enter A Name For An Evil Boss ")
print("Evil Boss: Hi" , name)
print("I Know Your Stuck On" , level1)
print ("Evil Boss: I Will Be On" , level3)
print ("Evil Boss: Can't Wait To Destroy You From" ,  boss)
print ("You: Let's Go To The Weapon Store!")
print ("Owner Of Store: What Weapon Would You Like" , name)
weapon = input ("Enter A Weapon Name")
print ("Owner Of Store: AHAH! Excellent Choice The" , weapon")
print ("Owner Of Store: Since Your On SUCH An Important Mission You Can Have It For FREE!")
print ("You: Thank You Owner Of Store")
print ("Owner Of Store: Your Welcome!")
