name = input ("Enter A Name")
level1 = input ("Enter A Place Name")
level2 = input ("Enter Another Place Name")
level3 = input ("Enter Another Place Name")
level4 = input ("Enter Another Place Name")
boss = input ("Enter A Name For An Evil Boss")
print("Hi" , name)
print("I Know Your Stuck On" , level1)
print ("I Will Be On" , level3)
print ("Can't Wait To Destroy You" ,  boss)
print ("Let's Go!")
