name = input ("Enter A Name ")
level1 = input ("Enter A Name For Level 1 ")
level2 = input ("Enter A Name For Level 2 ")
level3 = input ("Enter A Name For Level 3 ")
level4 = input ("Enter A Name For Level 4 ")
boss = input ("Enter A Name For An Evil Boss ")
print("Evil Boss: Hi" , name)
print("I Know Your Stuck On" , level1)
print ("Evil Boss: I Will Be On" , level3)
print ("Evil Boss: Can't Wait To Destroy You From" ,  boss)
print ("You: Let's Go To The Weapon Store!")
print ("Owner Of Store: What Weapon Would You Like" , name)
weapon = input ("Enter A Weapon Name ")
print ("Owner Of Store: AHAH! Excellent Choice The" , weapon)
print ("Owner Of Store: Since Your On SUCH An Important Mission You Can Have It For FREE!")
print ("You: Thank You Owner Of Store")
print ("Owner Of Store: Your Welcome!")
print ("You: Hey A Key!")
print ("You: It's Magic! Abra Kadabra")
print ("You: Woah I'm On" , level2)
print ("You: I'm Feeling Lonely I'm Gonna Get A Magical Pet!")
print ("Owner Of Store: Hello Again" , name)
print ("You: You Own This Store Too?")
print ("Owner Of Store: Yeah I Have A Lot Of Money")
print ("Owner Of Store: So What Pet Can I Get You?")
pet = input ("Enter The Type Of Animal You Would Like To Have As A Pet ")
print ("Owner Of Store: AHAH! Excellent Choice A" , pet)
print ("Owner Of Store: Now Give It A Name")
petname =  input ("Enter A Name For Your Pet ")
print ("Hello" , petname)
